KOD-8.3: given try-catch-finally to handle exceptions from FlightSear…
barteknat/barteknat-kodilla pull request #16
Opened 2021-02-07 20:17 UTC by barteknat

…ch class

2021-02-08 02:09 UTC, mps4dev requested changes
Proponuje ta mape dac w konsyruktorze.
Poza tym chyba program.nie zadziala tek jal powinien. Co jesli w mapie bedzie wiecej wpisow?

2021-02-09 00:57 UTC, mps4dev requested changes
👎

2021-02-09 00:57 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearch.java
> +            } else {
kombinujesz

2021-02-09 00:57 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearch.java
> +        flights.put("Rome", true);
mapa ma przyjsc w konstruktorze a nie byc zainicjowana w konstruktorze. Czyli mapa ma byc parametrem konstruktora.

2021-02-09 00:57 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearch.java
> +        flights.put("Lisbon", true);
te dane sobie zainicjujesz we FlightRunner

2021-02-09 00:57 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearch.java
> +            } else {
skorzystaj z dobrodziejstw mapy. metoda containsKey() i get() wystarczy (a nawet samo get by wystarczylo) - mam nadzieje, ze cie nakierowalem

2021-02-09 00:57 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearch.java
> +        boolean airportOpen = true;
powyzsze zmienne lokalne nie beda nam potrzebne

2021-02-09 05:31 UTC, barteknat commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearch.java
> +            } else {
Tyle, ze samo get będzie uzależniało wynik walidacji od wartości true albo false z argumentu value, jeśli tak to zadanie jest prostsze tylko źle sformułowane, bo wyraźnie jest napisane w treści, ze należy rzucić wyjątkiem jak lotnisko nie będzie istnieć w mapie, a nie jak będzie miało wartość false

2021-02-10 00:25 UTC, mps4dev requested changes
Proponuje wrocic do tematu na spotkaniu. Metoda find nie moze zwracac void. W mapie sa wartosci typu Boolean, wiec wystarczy zwrocic mapa.get(klucz)

2021-02-10 18:32 UTC, barteknat commented
> Proponuje wrocic do tematu na spotkaniu. Metoda find nie moze zwracac void. W mapie sa wartosci typu Boolean, wiec wystarczy zwrocic mapa.get(klucz)

2021-02-11 11:13 UTC, mps4dev requested changes
👎

2021-02-11 11:13 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearch.java
> +    public String findFlight(Flight flight) throws RouteNotFoundException {
boolean

2021-02-11 11:13 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearch.java
> +        try {
if (flights.containsKey(flight.getArrivalAirport())) return flights.get(flight.getArrivalAirport());
throw new RouteNotFoundException();

2021-02-11 19:25 UTC, mps4dev requested changes
👎

2021-02-11 19:25 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearchRunner.java
> +            if (new FlightSearch(flights).findFlight(new Flight("Warsaw", "Madrid")) == true) {
uproscic ifa

2021-02-11 19:25 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearchRunner.java
> +
FlightSearch flightSearch = new FlightSearch(flights);
Flight flight = new Flight("Warsaw", "Madrid");
try {
     if (flightSearch.findFlight(flight)) {
          System.out.println("It is possible to get to " + flight.getArrival());
     } else {
     System.out.println("It is not possible to get to " + flight.getArrival());
     }
} catch (RNFE e) {
 System.out.println("Flight to " + flight.getArrival() + " not found in database");
} finally {
sout("Dziekujemy za skorzystamnie z naszych uslug)
}

2021-02-11 19:29 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearchRunner.java
> +        Map<String, Boolean> flights = new HashMap<>();
a moz zrobic metode prywatna statyczna initFlights()?

2021-02-11 19:31 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearchRunner.java
> +    }
ptivate static Map<String, Boolean> initFlightsMap() {
Map<String, Boolean> flights = new HashMap<>();
flights.put("Rome", true);
        flights.put("Madrid", true);
        flights.put("London", false);
        flights.put("Paris", false);
        flights.put("Lisbon", true);
        flights.put("Berlin", false);
return flights;
}

2021-02-11 19:31 UTC, mps4dev commented on kodilla-exception/src/main/java/com/kodilla/exception/test3/FlightSearchRunner.java
> +
FlightSearch flightSearch = new FlightSearch(initFlights());

2021-02-13 15:43 UTC, mps4dev approved these changes
👍

2021-06-10 21:36 UTC, merged