added implementation for library median count
barteknat/barteknat-kodilla pull request #49
Opened 2021-07-26 21:13 UTC by barteknat

2021-07-27 09:27 UTC, mps4dev requested changes
Żadne BookA i BookB. Załóżmy, że dostajesz te klasy w bibliotekach. Nie możesz im zmienić nazw.

2021-07-27 09:27 UTC, mps4dev commented on kodilla-pattern2/src/main/java/com/kodilla/patterns2/adapter/bookclassifier/MedianAdapter.java
> +        for (BookA bookA : bookASet) {
a stream by byl taki ladny tutaj

2021-07-27 09:34 UTC, barteknat commented
> Żadne BookA i BookB. Załóżmy, że dostajesz te klasy w bibliotekach. Nie możesz im zmienić nazw.

2021-08-31 12:07 UTC, mps4dev approved these changes

2021-08-31 18:16 UTC, merged